### ISSUE TITLE
Package does not work caused by wrong URL

### ISSUE THREAD

**Issue by Xarvalus** [laki944/react-native-navigation-directions#14]
Code generates broken link (URL notation mismatch) which doesn't pass all parameters properly, in effect opening web browser with improper link.

Please merge fix https://github.com/laki944/react-native-navigation-directions/pull/12

Instead we are forced to work on our forks.

**Comment by laki944** [comment]
Hello,

I did not have time to test PR, but i merged #12 right now.

**Comment by milankamilya** [comment]
Please release this rectification on npm package

**Comment by laki944** [comment]
> Please release this rectification on npm package

Version 1.0.3 is released on npm.

**Comment by milankamilya** [comment]
Thanks
