### ISSUE TITLE
cannot set startPoint to 'null'

### ISSUE THREAD

**Issue by thinei** [laki944/react-native-navigation-directions#7]
![null](https://user-images.githubusercontent.com/22386168/36466276-a66d16b4-1707-11e8-93c8-b09f7438ba6a.jpg)

set startPoint to "null" cause the problem of "null is not an object" error
How can I get my current location on Map? 

![error](https://user-images.githubusercontent.com/22386168/36466712-dd4cf67a-1709-11e8-82e7-a8fc4a48c6e5.jpg)

![pic 1](https://user-images.githubusercontent.com/22386168/36466442-a203a330-1708-11e8-9791-e8449757d393.jpg)

p.s.   It's OK when use static latitude and longitude values in startPoint

**Comment by championboylay** [comment]
Same to me!

**Comment by laki944** [comment]
Ok, i will check what's happening.

**Comment by thinei** [comment]
Thanks for your help to release new version with error fixing, but getting startPoint error still causing when linking. 
I used Geolocation.getCurrentPosition()  to get the current position of the device.
It's OK to me.
