### ISSUE TITLE
Choose apple or google maps?

### ISSUE THREAD

**Issue by aliy321** [laki944/react-native-navigation-directions#9]
Is there a way to choose which one to open?

**Comment by laki944** [comment]
No, for now it's not possible.
.

**Comment by aliy321** [comment]
I changed the link in your code to googlemaps instead of apple and it works.

**Comment by vivekshah-zymr** [comment]
@aliy321  I want to open a popup which asks for google map/Apple map. Have you any workaround for this?

**Comment by aliy321** [comment]
> @aliy321 I want to open a popup which asks for google map/Apple map. Have you any workaround for this?

Might need to change his file, maybe you can tweak the platform code either ios/google
